# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b9352693cdbea4134313f165fa748848495f3bc97b11dc4d31bc700db49ca9030e5922412c888d292c0ab5bd1964b8766c31da2c7a4436b6cd0359554191603

test:
  secret_key_base: 94849f81e1ba8866b0f38c0af28da2d21bcc22f2a663cd5ba09eb698786ef20e19474e8acdd7a8f271cd196ecae38b201111c28526671002987021c9ad1ff047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
